Mohsina-Ahmed/MLA-pilot-group-2

package-lock.json

Test pull request

---

frontend/src/components/footer.js

Changes to footer

---

activity-tracking/models/exercise.model.js
activity-tracking/routes/exercises.js
frontend/src/components/trackExercise.js

Sprint 1 tasks for activity tracking microservice:
Addition of:
- Distance metric
- Emojis to track mood
Changes:
- Switching order of fields
- Changing description field to a title.

Adding new fields and changing orders in track exercise page.

---

activity-tracking/models/exercise.model.js
frontend/src/App.css
frontend/src/components/trackExercise.js

Merging gbTask3 branch.
Changes:
- On selection of 'Other' dropdown menu provides selection of new activities to choose.
- When other activity selected, shown at top of form.
- Re-adding 'Title your activity' label.
- Adjusting spelling error for 'Other activity' label.

Adding new activities to choose

---

activity-tracking/models/exercise.model.js
activity-tracking/routes/exercises.js
frontend/src/App.css
frontend/src/components/trackExercise.js

Merging gbTask4 branch.
Changes:
- Calculation of speed using distance and duration states
- Addition of speed field for all activities except Gym
- Adding tooltip so user knows it is auto-calculated for them
- Fixing to 2dp.

Adding auto-calculating speed field

---

analytics/app.py
frontend/src/components/journal.js
frontend/src/components/trackExercise.js

easy win ticket. make date format more readable
changes to: 
- app.py 
- journal.js
- trackExercise.js

Updated date format to DD-MM-YYYY 

---

.vscode/launch.json
analytics/app.py
frontend/src/components/journal.js
frontend/src/components/trackExercise.js

update date format for readability 
changes to: 
- app.py
- trackExercise.js
- journal.js
confirmed database functioning locally.

update date format revised

---

frontend/src/components/homepage.js

Please kindly review alongside with navbar.js changes, changes to App.js

Change to Homepage file

---

frontend/src/App.js
frontend/src/components/homepage.js

Added Homepage component into App.js

Change to App.js file to add a new Homepage Component

---

frontend/src/components/homepage.js

Bug fix to Homepage.js
fixed the missing import of useEffect.

Bug fix to Homepage.js

---

frontend/src/components/navbar.js

Sprint 1: My task was to add a highlight when a Nav link is clicked.
-  I used the local state to keep track of the currently active link and apply a specific style to it. 
- added a variable activeLink to keep track of the currently active link.
- When a Nav link is clicked, it sets the activeLink state to the clicked linkIn each Nav link, 
- Applied the 'active' class based on whether the link matches the activeLink state.

Urs Sprint One Highlight on Click Update navbar.js

---

frontend/src/App.css

The "!important" rule ensures that this style takes priority over other styles defined The active link is styled

App CSS Style for highlight on click, changes to blue and bold

---

authservice/src/main/java/com/authservice/auth/controller/AuthController.java
authservice/src/main/java/com/authservice/auth/service/SignUpService.java

The new authentication regulations have been added. 
1. Add at least 1 uppercase letter
2. Add at least 1 digit
3. Add at least 1 special character.

Adding Authservices

---

mongodb/Dockerfile
mongodb/README.md

I have added volume into Dockerfile to persist data.

Adding volume into Dockerfile to persist data

---

frontend/src/config.js

Added fargate IP to config.js for frontend to get access.

Adding Fargate ip to config.js

---

frontend/src/components/homepage.js

I have merged Urs' s homepage by mistake. The one she was testing, so reverting it back to the previous one.

reverting homepage to old one

---

authservice/src/main/java/com/authservice/auth/controller/AuthController.java

I have added Urs testing Navbar code by mistake from my branch to main. Now removing them.

Removing Urs Navbar, that was added by mistake

---

.vscode/launch.json
docker-compose.yml
frontend/Dockerfile
frontend/README.md
frontend/src/config.js
nginx/Dockerfile
nginx/default.conf

Nginx port has been changed to 443. To run the app locally please make sure you have .env file inside frontend -> src.
Inside the .env file, you should have: 
REACT_APP_API_GATEWAY_URL=http://localhost:443

Nginx update2

---

frontend/README.md

Reverting to old config for nginx

---

frontend/src/config.js

fixing config.js

---

frontend/src/config.js

Adding Alias for localhost: 127.0.0.1

adding alias for localhost

---

frontend/src/config.js

updating config.js

---

activity-tracking/models/exercise.model.js
frontend/src/components/trackExercise.js

Changes to trackExercise.js:
- Addition of custom activity option to exercise list, this allows user to enter any activity type.
- Addition of walking exercise type as an icon
- Change other icon to a plus icon - more clear for the user
exercises.js - class updated to remove enumerate list of exercise types so that user can type any.

Changes to track exercise to improve inclusivity.

---

docker-compose.yml
prometheus/prometheus.yml

Added prometheus and grafana to the codebase.

Grafana / prometheus

---

activity-tracking/models/exercise.model.js
activity-tracking/routes/exercises.js
frontend/src/App.css
frontend/src/components/trackExercise.js
frontend/src/components/trackExercise.test.js
frontend/src/components/userProfile.js

Calories burnt calculation:
- Adding intensity and calories properties to exercise class.
- Adding intensity to track exercise page, using range slider.
- Implementing calories calculation based on user weight, intensity + 2 (to get a MET value), and duration.
- Added calories calculation as test case in jest file.
Accessibility:
- Adding aria-labels to track exercise page and user profile page, to improve accessibility for usage of screen readers.
Inclusivity:
- Adding Walking as an icon.
- Adding custom exercise option to improve inclusivity across all exercise types.

Adding calories burnt calculation and improvements for inclusivity and accessibility.

---

frontend/src/App.css
frontend/src/components/signup.js
frontend/src/components/userProfile.js

Minor tweaks to frontend style.

Tidying up styling for frontend and adding signup header

---

frontend/src/App.css
frontend/src/components/homepage.js
frontend/src/components/navbar.js

https://github.com/Mohsina-Ahmed/MLA-pilot-group-2/assets/147421076/6d54cb2f-9762-4d63-b544-57c901beec64

Colour change of navbar upon emoji click.

---

frontend/src/components/navbar.js
frontend/src/components/userProfile.js

Adjusting navbar width to fix it to app size.
Also minor update to weekly goals on user profile.

Minor fixes for navbar.

---

frontend/src/components/homepage.js

Adding last exercise schema to homepage and improvements to design.

---

.vscode/launch.json
analytics/app.py
analytics/schema.graphql
docker-compose.yml
frontend/src/components/queries/graphql.js
frontend/src/components/statistics.css
frontend/src/components/statistics_v2.js

- clean up of app.py to remove duplicate functions
- update statistics front end to use Apollo client useQuery 
- add dropdown to stats page to display selected activity 
- add daily calories schema

clean up app.py, add calories schema

---

analytics/app.py
analytics/schema.graphql
docker-compose.yml
frontend/src/components/queries/graphql.js
frontend/src/components/statistics.css
frontend/src/components/statistics_v2.js

improve stats page by including user information for tracked activities and record. 
- created to graphql query for stats records
- update frontend statistics to display stats information 
- resolve typo in calories query. 
- update graphql queries to use Floats to handle decimal values

update to stats page

---

frontend/src/components/homepage.js
frontend/src/components/queries/graphql.js

Radial chart of daily calories added to the homepage.
Finalised styling of the homepage and the personalization of colour theme.

Adding daily calories to the homepage.

---

authservice/src/main/java/com/authservice/auth/controller/AuthController.java
authservice/src/main/java/com/authservice/auth/service/SignUpService.java
frontend/src/components/homepage.js
frontend/src/components/userProfile.js

Changes to auth backend:
- SignUpService.java - adding in string patterns to check email address is valid and that dob is in DD/MM/YYYY format and is a valid date.
- AuthController.java - calling validation services for the /signup and /profile endpoints. Returns error message for user alerts.
Changes to signup.js and userProfile.js pages:
- Frontend end changes to check for errors when validating the email address and dob input by user.
- Adding alerts so the user knows why validation fails.
Misc update to homepage.js:
- Adding refetch for graphQL query.

Adding verification checks of email and dob to signup and user profile.

---

activity-tracking/models/goal.model.js
activity-tracking/routes/goals.js
analytics/app.py
analytics/schema.graphql
frontend/src/components/homepage.js
frontend/src/components/queries/graphql.js
frontend/src/components/userProfile.js

User Profile:
- Changes to add in a exercise aim (fitness, weight loss etc), and a daily calories goal.
- Adding these values to exercise class in activity tracking backend.
Analytics backend:
- Set-up for schema to retrieve the daily calories goal.
Homepage:
- Retrieving goal via graphql schema.
- Changes to frontend to use goal on radial chart.

Adding daily calories goal, and schema to show on homepage.

---

analytics/README.md
analytics/app.py
analytics/requirements.txt
analytics/schema.graphql
analytics/test_app.py
frontend/src/components/homepage.js
frontend/src/components/journal_v2.js
frontend/src/components/queries/graphql.js

clean up of the analytics service. removed unused functions and queries.
updated Readme.md 
expand pytest unit tests for new queries.

update analytics service and pytest

---

.vscode/settings.json
analytics/app.py
analytics/schema.graphql
frontend/src/components/journal_v2.js
frontend/src/components/queries/graphql.js
frontend/src/components/statistics.css
frontend/src/components/statistics_v2.js
frontend/src/components/trackExercise.js

- resolve graphql update when new activities logged using the fetch policy
- cleaned up import statements
- attempted to improve re-render when data updated - maintaining container size and waiting for loading state - prior to this the page would always reset (scroll bar at top). 
- update track exercise calendar to week start on monday.

improve journal / stats render
